### ISSUE TITLE
IBM has the best offer with a 2 CPU machine for K8s

### ISSUE THREAD

**Issue by mikekuzak** [Neutrollized/free-tier-gke#1]

**Comment by Neutrollized** [comment]
There's a reason why it's not even in the same conversation as the three that I mentioned: because it's IBM.

I guess if we're basing the criteria purely on cost of a **single node** k8s cluster, then I guess yeah, you can get an IBM k8s cluster for free, but I'm willing to bet that most people out there would rather pay the $4USD/mth and put it on GCP instead -- especially since there's so many other free tier services you can leverage from GCP.

And what if I wanted to scale up the number of nodes to do some testing?  With the free tier GKE, you can quite easily and it would cost you another $4 (or $8 if we're comparing apples to apples here with a 2CPU/4GB node) per month.  How much would it be to do the same on IBM cloud?  Let's take a look...well, if you break out of their 1 node free tier, then you'll have to pay for additional nodes at the regular price of -- wait...what?  Does that say [$0.11USD/hr!?!?!](https://www.ibm.com/ca-en/cloud/container-service/pricing) ...which is $80USD/mth.

**Comment by mikekuzak** [comment]
you can use the argument of cost, nevertheless your article was about free tries. But what does that mean "because it's IBM"? Some kind of bias?

**Comment by Neutrollized** [comment]
Yeah, my article was about free tiers and a "no management fee for one zonal cluster per billing account" is part of Google's "Always Free" tier -- I didn't put a click-bait description or repo name saying that everything was entirely free.  In fact, I lead off with "it's not 100% free", so I'm not sure which part of the repo name, description or opening paragraph you miscomprehended.

As for "because it's IBM", it's not bias -- they're not in the same league as GCP, AWS or Azure.  It's not so much as a knock as it is the truth; they're late to the cloud game, they don't have the same deep pockets, which trickles down and affects everything else from infrastructure, to people, to innovation.  If Google and IBM were to offer you a engineering role with them with everything the same (JD, title, stock, bonuses), heck let's say IBM throws in an extra $5k signing bonus.  Who will you go with?  At this juncture in our spirited back and forth, you might say IBM just to try and spite me, but I'm sure the overwhelming majority would go with Google and the reason would be simple: "Because it's Google."


*EDIT:* bottom line is that I put this out there for people to use as an option if they want a fully managed k8s cluster from one of the big 3.  I'm not forcing people to use it; you don't like it and want to use IBM cloud's k8s (or from any other provider), that's your prerogative.  if you want to setup a repo with a price breakdown of every managed k8s service option out there, be my guest.
