### ISSUE TITLE
google_compute_subnetwork INTERNAL_HTTPS_LOAD_BALANCER renamed to REGIONAL_MANAGED_PROXY?

### ISSUE THREAD

**Issue by darvelo** [Neutrollized/free-tier-gke#5]
New to GCP and Terraform so still trying to figure things out. Was using k8s on minikube with skaffold but now preparing to deploy my app live on GCP.

I'm wondering if I can make the `google-beta` provider unused since it seems `INTERNAL_HTTPS_LOAD_BALANCER` is no longer a `purpose` type. It's not in the Terraform documentation and the GCP docs recommend migrating to `REGIONAL_MANAGED_PROXY`: https://cloud.google.com/load-balancing/docs/proxy-only-subnets#migrate-purpose

Is all this correct? Still haven't finished adapting your config to my app structure and testing deploy and all the various docs are a bit overwhelming to me at this stage so it's hard for me to know for sure.

Thanks for this incredibly helpful work.

**Comment by darvelo** [comment]
Ah, I see [autoscaling_profile](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#autoscaling_profile) is still in beta, so `google-beta` must persist for now. 😄

**Comment by Neutrollized** [comment]
Thanks for bringing this up.  It hasn't be updated because it hasn't been an issue and the `INTERNAL_HTTPS_LOAD_BALANCER` is still accepted.  If you see [note](https://cloud.google.com/load-balancing/docs/proxy-only-subnets#proxy_only_subnet_create) from Google's documentation they say that `REGIONAL_MANAGED_PROXY` is the preferred name, so perhaps I should update this sooner rather than later

**Comment by darvelo** [comment]
OK, thanks for letting me know I'm on the right track! All is provisioned now, thank you so much!
